---
# Cross-platform defaults. Update these to match your tools.

common_packages:
  - git
  - curl
  - unzip

linux_packages:
  - build-essential
  - zsh

homebrew_taps:
  - anomalyco/tap
  - oven-sh/bun

linux_brew_packages:
  - anomalyco/tap/opencode
  - fnm
  - neovim
  - oh-my-posh
  - tree-sitter-cli
  - yazi
  - 1password-cli
  - uv
  - oven-sh/bun/bun
  - gcloud-cli

macos_brew_packages:
  - git
  - curl
  - zsh
  - fnm
  - neovim
  - anomalyco/tap/opencode
  - oh-my-posh
  - tree-sitter-cli
  - yazi
  - 1password-cli
  - uv
  - python@3.13
  - oven-sh/bun/bun

macos_cask_packages:
  - gcloud-cli

oh_my_posh_install_font: true
oh_my_posh_font: meslo

go_version: "1.26.0"

rustup_default_toolchain: stable
rustup_profile: default

fnm_node_version: "25.6.1"
