version = 3

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "black"
  background = "cyan"
  template = " OMP "

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "cyan"
  template = " {{ .Path }} "

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "green"
  template = " {{ .HEAD }}{{ if .Working.Changed }}*{{ end }} "

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  foreground = "yellow"
  template = "{{ .FormattedMs }} "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "magenta"
  template = "> "
